config/routes.rb
Rails.application.routes.draw do

  # Authentication
  # @implemented
  devise_for :users

  # Application
  # @implemented
  root to: 'home#index'
  resource :newsletter, only: [:create]
  resource :contact, only: [:new, :create]

  # Dashboard
  # @implemented
  namespace :dashboard do
    get '', to: 'home#index'
    resources :editions do
      resources :editals
      resources :subscriptions
      resources :approveds
    end
    resources :newsletters
    resources :posts
  end
end

app/models/application_record.rb
# sanitizer:string
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# sanatize:string
class Category < ApplicationRecord
  include Filterable

  self.table_name = 'categories'
  self.primary_key = 'id'

  belongs_to :user

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :description,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }

  validates :tags,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 75 }
end

app/models/contact.rb
# sanitizer:string
class Contact
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include Mailer

  attr_accessor :name, :phone, :email, :message

  def initialize(params: {})
    @name = params[:name]
    @phone = params[:phone]
    @email = params[:email]
    @message = params[:message]
  end

  def persisted?
    false
  end

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :phone,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 15 }

  validates :email,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }

  validates :message,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 2000 }
end

app/models/edition.rb
# sanatize:string
class Edition < ApplicationRecord
  belongs_to :user
end

app/models/newsletter.rb
# sanitizer:string
class Newsletter < ApplicationRecord
  include Mailer

  self.table_name = 'newsletters'
  self.primary_key = 'id'

  scope :registered, -> { where(status: true) }
  scope :unregistered, -> { where(status: false) }

  def signup
    self.token = SecureRandom.urlsafe_base64
    self.status = true
    self.confirmed_at = Date.today
  end

  def cancel
    self.token = nil
    self.status = false
  end

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :email,
            presence: true,
            uniqueness: true,
            allow_blank: false,
            length: { minimum: 3, maxmimum: 245 }

  validates :token, uniqueness: true
end

app/models/post.rb
# sanatize:string
class Post < ApplicationRecord
  include Filterable

  self.table_name = 'posts'
  self.primary_key = 'id'

  scope :recents, -> { where(created_at: :desc).limit(3) }
  scope :by_user, -> (user) { where(user_id: user.id) }

  # Relationships
  belongs_to :user

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :description,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 145 }

  validates :content,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimu: 3, maximum: 4000 }

  validates :tags,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 80 }
end

app/models/user.rb
# sanatize:string
class User < ApplicationRecord
  self.table_name = 'users'
  self.primary_key = 'id'

  # Relationships
  # @implemented
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

# sanitize:string
class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/_form.html.erb
<%= form_for(@contact, {url: contact_path, method: :post}) do |f| %>
  <div class='field'>
    <div class="col-md-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: 'required',
      placeholder: 'Digite o nome', autocomplete: 'off' %>
    </div>
  </div>
  <div class="field">
    <div class="col-md-6">
      <%= f.label :phone %>
      <%= f.text_field :name, class: 'form-control', required: 'required',
      placeholder: 'Digite o e-mail', autocomplete: 'off' %>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.label :email %>
      <%= f.email_fied :email, class: 'form-control', required: 'required',
      placeholder: 'Digite o e-mail', autocomplete: 'off' %>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.label :message %>
      <%= f.text_area :message, class: 'form-control', required: 'required',
      placeholder: 'Escrevea sua mensagem', autocomplete: 'off' %>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.submit 'Enviar Mensagem', class: 'btn btn-primary btn-lg top' %>
    </div>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for(@contact, {url: contact_path, method: :post}) do |f| %>
  <div class='field'>
    <div class="col-md-6">
      <%= f.label :name %>
      <div class='input-group'>
      <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
      <%= f.text_field :name, class: 'form-control', required: 'required',
      placeholder: 'Digite o nome', autocomplete: 'off' %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="col-md-6">
      <%= f.label :phone %>
      <div class='input-group'>
      <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
      <%= f.text_field :name, class: 'form-control', required: 'required',
      placeholder: 'Digite o e-mail', autocomplete: 'off' %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.label :email %>
      <div class='input-group'>
      <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
      <%= f.email_field :email, class: 'form-control', required: 'required',
      placeholder: 'Digite o e-mail', autocomplete: 'off' %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.label :message %>
      <%= f.text_area :message, class: 'form-control', required: 'required',
      placeholder: 'Escrevea sua mensagem', autocomplete: 'off' %>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.submit 'Enviar Mensagem', class: 'btn btn-primary btn-lg top' %>
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<% provide :title, "Contato" %>

<section id='presenter' class='jumbotron'>
  <div class="container">
    <div class="row">
      <div class="col-md-12">

      </div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="col-md-12">

       <ul class='breadcrumb'>
          <li><%= link_to 'Home',    root_path %></li>
          <li><%= link_to 'Contato', new_contact_path %></li>
       </ul><!-- list-unstyled -->

       <%= render 'form' %>

    </div><!-- col-md-12 -->
  </div><!-- row -->
</div><!-- container -->

app/views/dashboard/home/index.html.erb
<h1>Dashboard::Home#index</h1>
<p>Find me in app/views/dashboard/home/index.html.erb</p>

app/views/home/index.html.erb
<% provide :title, "Home" %>

app/views/layouts/_footer.html.erb
<footer class='jumbotron'>
  <div class="container">
    <div class="row">
      <div class="col-md-12">

      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">CEPSR</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Cursinho CEPSR', '' %></li>
          <li><%= link_to 'Ensino', '' %></li>
          <li><%= link_to 'Suporte ao Ensino', '' %></li>
          <li><%= link_to 'Concursos', '' %></li>
          <li><%= link_to 'Contato', new_contact_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"></a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='cepsr'>
  <head>
    <title>CEPSR | <%= yield :title %></title>
    <meta charset='utf-8'>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style><%= yield :css %></style>
    <script><%= yield :js %></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'
    ng-app='ApplicationController as appCtrl'>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html ng-app='cepsr'>
  <head>
    <title>CEPSR | <%= yield :title %></title>
    <meta charset='utf-8'>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style><%= yield :css %></style>
    <script><%= yield :js %></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'
    ng-app='ApplicationController as appCtrl'>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>